### ISSUE TITLE
Updating to Latest Foundation?

### ISSUE THREAD

**Issue by hellorich** [pattern-lab/starterkit-mustache-foundation#1]
Hi!

I notice this uses Foundation 6.0.1 according to dist/js/foundation.js. Given the lack of watchers I'm guessing there's not much chance this will be updated soon yeah?

I was wondering if any of you could give a brief summary of what would be required to fork and update this myself if a project I'm working on decides to use it so I wouldn't be going in completely blind? Any do's and don't's would be much appreciated.

Obviously I'd be happy to submit any work we do back here.

Thanks!

**Comment by dmolsen** [comment]
@hellorich -

Yeah, doubt it gets updated. Sorry. I'd download a zip of this and create a repo from that rather than try to fork.

Anyone can create a StarterKit. Anything in `./dist` will get put into your source directory in Pattern Lab. You'll need the four directories that start with an underscore but otherwise you can organize things whichever way you like (e.g. `./dist/stylesheets/` instead of `./dist/css`). If you're using the node version of PL make sure there's a `package.json` and if you're using the PHP version definitely make sure you include a `composer.json` that follows the convention here.

Hope this helps.

**Comment by hellorich** [comment]
@dmolsen Cool, thanks for the advice :)

**Comment by bradfrost** [comment]
@hellorich I think maybe @dmolsen was a little too dismissive about this. I'd personally love it if people like you who care about Foundation and Pattern Lab could help make the Pattern Lab Foundation starterkit rock solid. We have a start going, but if you'd be interested in rounding it out, we'd be happy to answer and questions and point you in the right direction. Does that sound like something you'd be interested in?

**Comment by hellorich** [comment]
@bradfrost It really depends on whether my client wants to go forward with utilising Pattern Lab. Certainly they were quite impressed when I presented it to them as a possible resource for their content editors and developers.

I'm back with them in a couple of weeks to update their codebase to the latest Foundation as they were using a slightly old version due to length of the project, so could be a good time to see if they have budget for setting up Pattern Lab too. I'll post back here if I get the go ahead.

Fingers crossed, and thanks for the offer of help :)
